### ISSUE TITLE
[ГРАФИКА] Будет ли дизайн закруглённым?

### ISSUE THREAD

**Issue by Jrol123** [Jrol123/Summer_practice-snake#7]
Скруглённой или острой?

**Comment by arapius** [comment]
Мне кажется, что стоит сделать туловище змеи квадратным (за исключением хвоста, он будет треугольным). Это очень упростит реализацию анимации поворота, так как фактически спрайты прийдется менять только у головы и хвоста

**Comment by arapius** [comment]
Мне кажется, что стоит сделать туловище змеи квадратным (за исключением хвоста, он будет треугольным). Это очень упростит реализацию анимации поворота, так как фактически спрайты прийдется менять только у головы и хвоста

**Comment by arapius** [comment]
![snake head st](https://github.com/Jrol123/Summer_practice-snake/assets/128876499/50871a95-0379-4ad6-b4e3-908a0dfafaf1)
![snake body](https://github.com/Jrol123/Summer_practice-snake/assets/128876499/c53f9258-1afc-4e7e-9078-9dc061f8c9a1)
![snake body](https://github.com/Jrol123/Summer_practice-snake/assets/128876499/42d0041a-4229-4f49-a2b1-b112142729ec)
![snake body](https://github.com/Jrol123/Summer_practice-snake/assets/128876499/e9486ac6-0c82-469c-84b1-582f642ffefd)
![snake tail st](https://github.com/Jrol123/Summer_practice-snake/assets/128876499/fb27f63b-2f87-42e8-abdb-f662568c9d0d)

**Comment by arapius** [comment]
Или можно вообще хвост убрать
Это еще больше упрощает ситуацию, так как фактически спрайты для поворота нам нужны будут только для головы
![snake head st](https://github.com/Jrol123/Summer_practice-snake/assets/128876499/84ef02d4-8c08-454e-bc90-fa8fddad6c36)
![snake head left](https://github.com/Jrol123/Summer_practice-snake/assets/128876499/7f9046d3-cc7f-4f48-b415-49bc12d50de5)
![snake head back](https://github.com/Jrol123/Summer_practice-snake/assets/128876499/0f737169-6093-4b62-997e-787e80621bc3)
![snake head right](https://github.com/Jrol123/Summer_practice-snake/assets/128876499/8cbb7461-6b41-4ac2-9a5b-2c4bb87bdf21)

**Comment by arapius** [comment]
и мне кажется анимировать такое будет проще

**Comment by Jrol123** [comment]
Будет закруглённым.
(см. textures)
