### ISSUE TITLE
[ГРАФИКА] Цвет змеи

### ISSUE THREAD

**Issue by Jrol123** [Jrol123/Summer_practice-snake#8]
Каким будет цвет змеи?

Предлагаю оранжевый.
![screen-6](https://github.com/Jrol123/Summer_practice-snake/assets/47931983/013d6571-6439-41c0-bf87-536b264a867d "Минималистично и понятно!")

**Comment by arapius** [comment]
Хорошо, мне нравится этот вариант, не будет с фоном сливаться
